config/routes.rb
Rails.application.routes.draw do
 root 'bills#index'
  
  resources :bills do
    resources :months
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
     belongs_to :month
end

app/models/month.rb
class Month < ApplicationRecord
    has_many :bill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  
  def index
    @bills = Bill.all
  end

  def show
     @bill = Bill.find(params[:id])
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)
    if @bill.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bill = Bill.find(params[:id])
  end

  def update
    @bill = Bill.find(params[:id])
    if @bill.update(bill_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy
    redirect_to root_path 
  end
  
  private
  def bill_params
    params.require(:bill).permit(:name, :price, :month_id)
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
    def index
        @months = Month.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/bills/_form.html.erb
    <%= form_with model: bill do |form| %>
    
        <%= form.label :month_id, "Mes" %>
        <%= form.collection_select :month_id, Month.all, :id, :name,{}, {class: "form-select"} %>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "form-control" %>
    
        <%= form.label :price %><br>
        <%= form.number_field :price, class: "form-control" %>
    
        <%= form.submit "Crear", class: "btn btn-success mt-3" %>
        <%= link_to "Volver a Lista", root_path, :class => "btn btn-primary mt-3" %>
    
    <% end %>

app/views/bills/edit.html.erb
<h1 class="display-4 text-center">Editar Cuenta</h1>

<%= render "form", bill: @bill %>

app/views/bills/index.html.erb
<h1 class="display-4 text-center"> Cuentas </h1>

<div class="row">
    <div class="col-4">
        <%= form_with do |f| %>
            <br>
            <%= f.collection_select :month_id, Month.all, :id, :name,{}, {class: "form-select"}%>
            <%= f.submit  "Buscar", class: "btn btn-primary btn-sm mt-3 form-control" %>
        <% end %>
    </div>
    
    <div class="col-8">
        <div class="card shadow rounded text-dark bg-light mt-4">
            <div class="card-header">
                <h5 class="card-title" id="nombreMes" ></h5>
            </div>

            <div class="card-body">
                <table class="table table-bordered text-center">
                <thead>
                    <tr>
                    <th>Fecha Pago</th>
                    <th>Cuenta</th>
                    <th>Monto</th>
                    <th>Opciones</th>
                    </tr>
                </thead>
                <% @bills.each do |bill| %>
                <tbody>
                    <tr>
                    <th><%= bill.created_at.strftime("%d/%m/%Y") %></th>
                    <td><%= bill.name %></td>
                    <td><%= bill.price %></td>
                        <td>
                            <%= link_to 'Editar', edit_bill_path(bill), class: 'btn btn-success btn-sm form-control' %>
                            <%= button_to "Eliminar", bill_path(bill), method: :delete, :class => "btn btn-danger btn-sm mt-2 form-control" %>
                        </td>
                    </tr>
                </tbody>
                <% end %>
                </table>
            </div>
        </div>
           <%= link_to "Agregar", new_bill_path, class: "btn btn-primary btn-sm form-control mt-2" %>
    </div>
</div>

<script type="module">
        const month = document.getElementById('month_id');
    
    // refresh the table when the month is changed
        month.addEventListener('change', function() {
        const monthId = month.value;
        const url = '/bills/' + monthId;
        window.location.href = url;
    });
</script>

app/views/bills/new.html.erb
<h1 class="display-4 text-center">Nueva Cuenta</h1>

<div class="row">
<%= render "form", bill: @bill %>
</div>

app/views/bills/show.html.erb
<h1><%= @bill.name %></h1>

<p><%= @bill.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <div class="container">
    <%= yield %>
  </div>
  
  </body>
</html>